version: "3.8"

services:
  office-db:
    image: postgres:12
    container_name: office-db
    restart: always
    environment:
      POSTGRES_USER: officeapp
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: office
    ports:
      - "5432:5432"
    volumes:
      - office_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U officeapp -d office" ]
      interval: 5s
      retries: 5
      start_period: 10s

  office-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: office-app
    restart: always
    ports:
      - "0:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://office-db:5432/office
      SPRING_DATASOURCE_USERNAME: officeapp
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      office-db:
        condition: service_healthy

volumes:
  office_db_data: