services:
  db:
    image: postgres:14
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: officeapp
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: office
    networks:
      - app-network

  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/office
      SPRING_DATASOURCE_USERNAME: officeapp
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
