version: "3.8"

services:
  office-db:
    image: postgres:12
    container_name: office-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: officeapp
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: office

  office-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: office-app
    restart: always
    ports:
      - "0:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/office
      SPRING_DATASOURCE_USERNAME: officeapp
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - office-db